feature: unrevised revs on user history page
serlo/frontend pull request #1311
Opened 2021-09-29 18:36 UTC by elbotho

2021-09-29 20:08 UTC, Entkenntnis commented
love it :heart: it has always been difficult to manage your own edits

2021-09-30 21:04 UTC, elbotho commented
okay peeps. 
it's now lives on it's own little page with a title and everything.
(menu entry can't be tested in this branch)

### Preview link:
- revisions: https://frontend-git-my-unrevised-serlo.vercel.app/entity/unrevised/user/141826/Renate_mit_vielen_Interessen
- no revisison: https://frontend-git-my-unrevised-serlo.vercel.app/entity/unrevised/entity/unrevised/user/600/maspengler

### menu entry:
![image](https://user-images.githubusercontent.com/1258870/135529798-b63ee56e-3536-4a12-bf70-1739cbb4371c.png)

### default view
![image](https://user-images.githubusercontent.com/1258870/135529690-91b62b65-8327-45cc-b574-3163b4df4f72.png)

### Own unrevised revisions (hides username in table)
![image](https://user-images.githubusercontent.com/1258870/135529601-a7816603-25a8-4828-a906-e31c8b8000cf.png)

### No revisions found
![image](https://user-images.githubusercontent.com/1258870/135529536-c40aaf74-9354-47ef-aa97-022ec215ccd7.png)

2021-10-01 08:11 UTC, kathongi commented
Looks great! There's only one (or two) thing(s) I would change. First: unrevised revisions? Isn't it unrevised changes in the english language version?
If we call the page "unrevised changes"/"ungeprüfte Bearbeitungen" it's confusing because we already have this page with **all** unrevised changes. Can we call it "my edits "/"Meine Bearbeitungen" instead?

2021-10-01 08:26 UTC, elbotho commented
Thanks, will check the english naming.
It's actually called `Meine Bearbeitungen` when you are on your own page.

Other people can theoretically also see the edits of this user, but we don't link to this page atm. and I would say that's another step.

2021-10-03 18:27 UTC, elbotho commented
@kathongi maybe `unrevised edits` would make sense, but we currently use `unrevised revisions` everywhere. So that's something we would need to discuss with the unit.

2021-10-04 08:19 UTC, kathongi commented
I only checked en.serlo.org and in the menu on the top right it says "unrevised changes".
"unrevised edits" sounds good to me.

2021-10-08 21:59 UTC, Entkenntnis requested changes
thank you! looks great and is working fine in localhost, ready for staging. same small feedbacks.

2021-10-08 21:59 UTC, Entkenntnis commented on src/fetcher/unrevisedRevisions/query.ts
> -export const unrevisedRevisionsQuery = gql`
kebap-case: rename folder -> `/unrevised-revisions/`

2021-10-08 21:59 UTC, Entkenntnis commented on src/data/de/index.ts
> +      title: "Ungeprüfte Bearbeitungen"
this menu entry is not working - as far as I am following the unrevised revisions are back in "Meine Aktivitäten" -> removing menu entry for all languages again?

2021-10-08 22:47 UTC, elbotho commented on src/data/de/index.ts
> +      title: "Ungeprüfte Bearbeitungen"
it's part of `index.ts` so it will get overwritten by sentry. will change other languages once it's merged.

2021-10-09 07:20 UTC, Entkenntnis commented
Have fun on staging :)

2021-10-09 07:20 UTC, merged

2021-10-13 11:47 UTC, yolo-bird commented
Looks good. From our side it is ready to go live in production. :-)

2021-10-13 11:51 UTC, elbotho commented
thanks @yolo-bird !