Change styling of SSO flow
serlo/frontend pull request #2303
Opened 2023-04-13 18:03 UTC by CodingDive

Fixes #2292 and most of #2282

Thank you to @elbotho for the suggestion of modifying the element order. I tried to make it as resilient as I could by defining an enum. I think this should be fixed in Kratos though and we shouldn't ideally have the need to change anything on the frontend or modify the order.

Need to figure out how I can make the SSO button get clicked. Right now it triggers the submit of the whole form.

- [x] clean up code
- [x] pass correct onSubmit to the `button` inside the `flow.tsx` or `node.tsx` component (unsure as of now on how to achieve this)

2023-04-13 19:38 UTC, elbotho requested changes
Thanks @CodingDive, added some questions and suggestions.

2023-04-13 19:38 UTC, elbotho commented on src/components/auth/node.tsx
> +          : 'Could not find translation'
`'Undefined'` as a fallback makes no sense here. Maybe use `node.meta.label.text`?
Also the label should not contain an error message. I guess if `node.meta.label` is actually not defined we should not render a button at all (any optinally trigger a sentry error).

2023-04-13 19:38 UTC, elbotho commented on src/components/auth/node.tsx
> +              {isLoading ? (
`isLoading` currently results in both buttons showing the animation which is a bit confusing.
Not sure what's the best way to solve that.

2023-04-13 19:38 UTC, elbotho commented on src/components/pages/auth/registration.tsx
> +    const reorderedNodes = origFlow.ui.nodes
did you check back if we can solve this at least partly in kratos?

2023-04-13 19:38 UTC, elbotho commented on src/components/pages/auth/registration.tsx
> +    }
basically just taste. It's  more fp but also more code.

2023-04-13 19:38 UTC, elbotho commented on src/components/pages/auth/utils.ts
> +export const changeButtonTypeOfSSOProvider = (uiNode: UiNode) => {
this is just annoying that kratos flow makes this necessary…

2023-04-13 19:38 UTC, elbotho commented on src/data/de/index.ts
> +        code1040002: 'Registriere mit NBP Account',
this will be removed in i18n. add to en file as well.

2023-04-13 21:18 UTC, Entkenntnis commented on src/components/pages/auth/utils.ts
> +} from '@ory/client'
putting these imports in this file is increasing bundlesize by 18kb (unfortunately, tree shaking is not able to shake code across different import trees)

Solution would be to move changeButtonTypeOfSSOProvider into a separate file and making it a separate module.

2023-04-14 13:24 UTC, CodingDive commented on src/components/pages/auth/registration.tsx
> +    }
Yeah, it's a little bit more resilient to changes from kratos in the future with a little bit more time complexity and code. I believe it's a good trade off, at least one can see the element order from the enum

2023-04-14 19:00 UTC, elbotho commented on src/components/pages/auth/registration.tsx
> +    }
Oh sorry, I just meant the actually marked lines. You could also modify the original object above and then you would not need to spread and modify here.

2023-04-25 10:11 UTC, CodingDive commented on src/components/auth/node.tsx
> +              {isLoading ? (
I disabled the loading spinner for the SSO provider button

2023-04-25 10:11 UTC, CodingDive commented on src/components/pages/auth/registration.tsx
> +    const reorderedNodes = origFlow.ui.nodes
I'll talk with Hugo about this

2023-04-25 11:24 UTC, elbotho commented
@CodingDive as of now this would block staging. 
Do you want to take on https://github.com/serlo/frontend/issues/2299 as well or should @Entkenntnis or me do that for now?

2023-04-25 12:10 UTC, CodingDive commented
> @CodingDive as of now this would block deploys. Do you want to take on #2299 as well or should @Entkenntnis or me do that for now?

@elbotho the experiments only work for logged in users as far as @Entkenntnis and I can tell. Once you're already logged in, it'd be quite hard to test SSO. Maybe we need another "experiment" solution for this that's not tied to user accounts.

I think it shouldn't block deploys because the "provider" UI element is coming from Kratos and production has a different configuration than staging. As a consequence, the button shouldn't appear in production, only staging (for now).

@Entkenntnis would like to try to deploy it tomorrow evening and see if there are any issues. I'll also be available to fix them.

2023-04-25 12:17 UTC, Entkenntnis commented
@CodingDive You can merge this branch into staging after checks are successful.

Please check crowdin and add german translations there as well - you can test it on staging then.

@elbotho As far as I see this should not change production and only difference in staging is an additional button.

2023-04-25 12:44 UTC, elbotho commented
Ah nice, if it actually does not change production behaviour we can probably skip that then.


> @elbotho the experiments only work for logged in users as far as @Entkenntnis and I can tell. Once you're already logged in, it'd be quite hard to test SSO. Maybe we need another "experiment" solution for this that's not tied to user accounts.

While the experiments interface is only visible for logged in users the features are actually stored in cookies and don't depend on the user-acc. So if we need this in the future we could either ask people to login once with a regular acc and activate the feature or make the experiment interface available outside of the own profile.

2023-04-25 15:21 UTC, elbotho approved these changes
Thank you @CodingDive, added one more comment, but I'm fine with testing this in staging.

2023-04-25 15:21 UTC, elbotho commented on src/components/pages/auth/ory-transforms.tsx
Since this does not use jsx this should be a `ts` file. 
Also: we have a convention where we do not export more than one thing from one file if possible and name the file like the exported function/component (with some exceptions for e.g. helper/utils files).

Maybe this code could  be part of `@/components/pages/auth/utils.ts`?

(backlog: maybe move utils.ts to `@/auth/`)

2023-04-25 15:31 UTC, CodingDive commented on src/components/pages/auth/ory-transforms.tsx
The reason why we put it in a separate file other than utils was because the bundle size got too big due to an import of @ory/client. I can rename the file to 'ory-helper'?

2023-04-25 15:41 UTC, elbotho commented on src/components/pages/auth/ory-transforms.tsx
I see, good that you checked bundle size.
`ory-helper.ts` or `kratos-helper.ts` would be fine for now then. thanks.

2023-04-25 15:43 UTC, elbotho commented on src/components/auth/node.tsx
> -          triggerSentry({
Missing translations are handled in `getKratosMessageString` already. 
I think it's save enough to trust that label is actually set (my guess is that it's just not an accurate type by kratos here).

2023-04-25 17:26 UTC, merged