Hotkey lib migration
serlo/frontend pull request #2598
Opened 2023-07-17 12:26 UTC by CodingDive

Closes https://github.com/edtr-io/edtr-io/issues/381

Attempt to make #2595 slimmer. Ctrl+Z / Ctrl+Y does not work in the editor so I'm marking it as a draft until I have found the fix.

2023-07-24 12:16 UTC, Entkenntnis commented
One bug I encountered:

![grafik](https://github.com/serlo/frontend/assets/13507950/c960e871-c43a-494b-9c25-980d4c4fc34f)

If you click "Füge ein Element hinzu", you can't navigate with arrow keys anymore. It's working on staging.

2023-07-24 12:22 UTC, Entkenntnis commented
In addition, now the behaviour of ctrl+z changed within text input.

Before: 

- Some <pause> Text 
- Ctrl-z
- Some

Now

- Some <pause> Text
- Ctrl + Z
- Some <pause> Tex

2023-07-26 18:15 UTC, elbotho commented
… interesting bug 🐛
If I press enter to create a new line, a new line appears all over the article.
url: https://frontend-git-refactor-migrate-react-hotkeys-serlo.vercel.app/entity/repository/add-revision/277232
in current chrome.
steps: I just press enter in the article introduction text plugin.

2023-07-26 18:32 UTC, CodingDive commented
> … interesting bug 🐛
> If I press enter to create a new line, a new line appears all over the article.

Thank you for finding it! Will take a look tomorrow 🥲

2023-07-26 19:14 UTC, hejtful commented
I didn't really understand, what is the plan with this ctrl+z/ctrl+y bug? Package maintainers don't plan to fix it soon, and this seems like a blocker for our undo/redo functionality. Maybe I misunderstood something, though 😄

2023-07-27 07:28 UTC, CodingDive commented
> I didn't really understand, what is the plan with this ctrl+z/ctrl+y bug? Package maintainers don't plan to fix it soon, and this seems like a blocker for our undo/redo functionality. Maybe I misunderstood something, though smile

The bug should be fixed but it's not as nice as it could be, see https://github.com/serlo/frontend/pull/2598/files#diff-ca29cee07474cdfa681d121c4bf0d502f667d84ca0097c3336b6e3bc431de021R88-R96

2023-07-27 08:37 UTC, elbotho commented
Also: `cmd+z` does not work at all for me in content-editable

2023-07-27 08:39 UTC, elbotho requested changes

2023-07-27 08:39 UTC, elbotho commented on src/serlo-editor/plugins/text/components/text-editor.tsx
> +    <div>
is this div needed?

2023-07-27 12:49 UTC, CodingDive commented on src/serlo-editor/plugins/text/components/text-editor.tsx
> +    <div>
Nice find, it slipped in from a ref that I had to attach previously and have since then removed :raised_hands:

2023-07-27 13:36 UTC, elbotho commented
Another big one: This completely breaks tab-navigation for me.

2023-07-27 18:12 UTC, Entkenntnis approved these changes
Thanks, looks good!

2023-07-27 18:59 UTC, elbotho approved these changes
yes 🎉 I finally only found a lot of bugs that were present before 😅
I think you can merge it into staging now. 

If you start on resolving the conflicts with https://github.com/serlo/frontend/pull/2571 please make sure that the PR is in a working state tomorrow since testing starts on this feature.

2023-07-27 19:01 UTC, CodingDive commented
Thank you everyone for testing and reviewing. Happy to finally merge this! 🙌

2023-07-27 20:01 UTC, merged