Split math code into multiple files
serlo/frontend pull request #2705
Opened 2023-08-07 21:47 UTC by CodingDive

Now that we have made some nice bug fixes and visual improvements with the math editor, I just took a few components/render fns and extracted them into their own files/components. 

Also put the DOM element selection into an effect for concurrent mode :tada:

2023-08-08 06:47 UTC, hejtful approved these changes
Nice!

2023-08-08 08:57 UTC, elbotho requested changes

2023-08-08 08:57 UTC, elbotho commented on src/serlo-editor/math/editor.tsx
> +    if (typeof window !== 'undefined') {
useEffect only runs on client so the check is not needed any more right?

2023-08-08 08:57 UTC, elbotho commented on src/serlo-editor/math/editor.tsx
> +                onMouseDown={() => void setIsHelpOpen(true)}
why do you prefer this?

2023-08-08 08:57 UTC, elbotho commented on src/serlo-editor/math/editor.tsx
> +function MathEditorOverlayPortal({
Why is this called `…OverlayPortal`? 
Also I think I'd prefer to have this in an own file now.

2023-08-08 08:57 UTC, elbotho commented on src/serlo-editor/math/math-help-modal.tsx
> +    <Modal
maybe follow up: using `ModalWithCloseButton` here would probably be a lot simpler.

2023-08-08 09:07 UTC, CodingDive commented on src/serlo-editor/math/editor.tsx
> +    if (typeof window !== 'undefined') {
No, that's useLayoutEffect. useEffect works on the server too

2023-08-08 09:07 UTC, CodingDive commented on src/serlo-editor/math/editor.tsx
> +                onMouseDown={() => void setIsHelpOpen(true)}
I just like to prefix booleans with "is", "has", etc. The `void` I like to symbolize that there is no return value.

2023-08-08 09:08 UTC, CodingDive commented on src/serlo-editor/math/math-help-modal.tsx
> +    <Modal
Oh, cool! Will take a look

2023-08-08 09:10 UTC, elbotho commented on src/serlo-editor/math/editor.tsx
> +    if (typeof window !== 'undefined') {
> Effects only run on the client. They don’t run during server rendering.

https://react.dev/reference/react/useEffect

2023-08-09 10:10 UTC, elbotho approved these changes
thanks for the improvement!

2023-08-09 11:32 UTC, merged