refactor(editor): Split richText formatting into 2 options
serlo/frontend pull request #2794
Opened 2023-08-27 16:40 UTC by AsterMiha

Previously, the richText formatting option included both bold and italic.
Since we would like to keep the default italic formatting of image captions, only the bold button should show up in the toolbar.
Now italic and bold formatting can be accessed separately through richTextBold and richTextItalic.

2023-08-27 16:58 UTC, hejtful requested changes
Smooth and clean changes 👍 

There is one small bug, table cells don't have bold and italic formatting options anymore. This might be [the relevant line](https://github.com/serlo/frontend/blob/staging/src/serlo-editor/plugins/serlo-table/editor.tsx#L32).

A weird thing is that [this line](https://github.com/serlo/frontend/blob/staging/src/serlo-editor/plugins/image/index.ts#L26) also contains the old `richText` option, but the caption works fine. Maybe that line can be removed completely? If not, then it might be good to update it with the new options.

2023-08-27 18:09 UTC, AsterMiha commented
> A weird thing is that [this line](https://github.com/serlo/frontend/blob/staging/src/serlo-editor/plugins/image/index.ts#L26) also contains the old `richText` option, but the caption works fine. Maybe that line can be removed completely? If not, then it might be good to update it with the new options.

The line doesn't seem to influence anything so I removed it

2023-08-27 18:53 UTC, hejtful approved these changes

2023-08-27 19:37 UTC, AsterMiha commented
> > A weird thing is that [this line](https://github.com/serlo/frontend/blob/staging/src/serlo-editor/plugins/image/index.ts#L26) also contains the old `richText` option, but the caption works fine. Maybe that line can be removed completely? If not, then it might be good to update it with the new options.
> 
> The line doesn't seem to influence anything so I removed it

A similar situation seemed to be happening with the box plugin as well

2023-08-28 08:21 UTC, elbotho approved these changes
Nice, thank you!

2023-08-28 08:52 UTC, merged