Reintroduce data wallet integration demo
serlo/frontend pull request #2890
Opened 2023-09-15 15:36 UTC by hugotiburtino

2023-09-19 17:00 UTC, elbotho requested changes

2023-09-19 17:00 UTC, elbotho commented on src/components/pages/data-wallet.tsx
> +                href="https://enmeshed.eu/use/basics"
url does not exist any more (domain sold).
Do we have a current link?

2023-09-19 17:04 UTC, elbotho commented on src/components/pages/data-wallet.tsx
> +              Lege in deiner Enmeshed App ein neues Profil an und füge Serlo als
Also here we should probably rename the app.

2023-09-19 17:07 UTC, elbotho commented
How can I test this? Do I need the local api setup or should it work on localhost with staging api already?

2023-09-19 17:16 UTC, hugotiburtino commented on src/components/pages/data-wallet.tsx
> +                href="https://enmeshed.eu/use/basics"
I saw it.
It is strange, since it was working the last days. I think they will fix it soon.
Anyway, I will change it to .de (thanks @hejtful for the suggestion).

2023-09-19 17:19 UTC, hugotiburtino commented
Thanks for your review 😊 

> How can I test this? Do I need the local api setup or should it work on localhost with staging api already?

You can use staging api already.
After scanning the QR code you should get an error, we are in contact with the integration team of them to clear this problem

2023-09-19 17:50 UTC, elbotho commented
Do you want this to work in production as well? Or only for staging?

2023-09-19 18:04 UTC, hugotiburtino commented
For now it is only for staging. The enmeshed endpoint won't work in the api
anyways.

On Tue, Sep 19, 2023, 19:50 Botho ***@***.***> wrote:

> Do you want this to work in production as well? Or only for staging?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/serlo/frontend/pull/2890#issuecomment-1726223353>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK6MCJJLJT56JAEU72BXY3TX3HLO3ANCNFSM6AAAAAA4Z7XBA4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-19 18:06 UTC, elbotho commented on src/pages/wallet.tsx
If you add a check for production here I'm happy to merge this :)

2023-09-19 21:32 UTC, elbotho approved these changes

2023-09-20 06:49 UTC, merged

2023-09-20 08:03 UTC, hugotiburtino commented on src/pages/wallet.tsx
Thanks for doing it ❤️