Feat/ai exercise generation
serlo/frontend pull request #3000
Opened 2023-10-18 08:30 UTC by Entkenntnis

2023-10-25 09:24 UTC, Entkenntnis commented on src/serlo-editor/plugins/exercise/editor.tsx
> +          <Experiment />
remove before merge

2023-10-25 09:24 UTC, Entkenntnis commented on src/pages/entity/create/[type]/[taxonomyId].tsx
> +  useEffect(() => {
todo: polish and comment @Entkenntnis

2023-10-25 09:25 UTC, Entkenntnis commented on src/data/en/index.ts
> +    },
-> loggedInData @CodingDive

2023-10-25 09:26 UTC, Entkenntnis commented on src/components/user-tools/edit-or-invite/tax-add-or-invite.tsx
> +  console.log('AuthorToolsData: ', data)
remove before merge @CodingDive

2023-10-25 09:27 UTC, Entkenntnis commented on src/components/taxonomy/topic.tsx
> +import { ExerciseGenerationWrapper } from '../user-tools/exercise-generation-wrapper'
@Entkenntnis dynamic load

2023-10-25 09:32 UTC, Entkenntnis commented on src/components/modal-with-close-button.tsx
> +      {alignTitleAndCloseButton ? (
most bundle size increase left is coming from here - probably fine ..

2023-10-25 10:16 UTC, Entkenntnis commented on src/data/en/index.ts
> +    },
it's fine to leave it there

2023-11-08 17:29 UTC, elbotho requested changes
some comments for now.

2023-11-08 17:29 UTC, elbotho commented on shared/tailwind-base.cjs
> +        lightgray: '#a3a3a3',
this is exactly `neutral-400`, why did you alias it?

2023-11-08 17:29 UTC, elbotho commented on shared/tailwind-base.cjs
> +        'background-gray': '#f2f2f2',
could you try `neutral-100` here and see if you can tell the difference? (and then maybe replace it)

2023-11-08 17:29 UTC, elbotho commented on shared/tailwind-base.cjs
> +        lightblue: '#b8e7ff',
also in the spirit of tailwind I'd suggest using `sky-200`

2023-11-08 17:29 UTC, elbotho commented on shared/tailwind-base.cjs
> +        lightskyblue: '#93c5fd',
and `blue-300`

2023-11-08 17:29 UTC, elbotho commented on shared/tailwind-base.cjs
> +  400: '#ffd8a6',
this one is almost perfectly `orange-200`

2023-11-08 17:29 UTC, elbotho commented on shared/tailwind-base.js
(same changes as above)

2023-11-08 17:29 UTC, elbotho commented on src/components/close-button.tsx
> +export const CloseButton: React.FC<CloseButtonProps> = ({
It's more a matter of taste/habit but before this PR there is no occurrence of `React.FC` in the frontend.
Almost all components are build like this:
```
function CloseButton({…}: CloseButtonProps) {}
```

While it's not a problem it feels a bit weird to me to have different personal styles for stuff like this in the same codebase.

2023-11-08 17:29 UTC, elbotho commented on src/components/content/exercises/exercise-generation-wizard.tsx
> +          <>
fragment can be removed

2023-11-08 17:29 UTC, elbotho commented on src/serlo-editor/plugins/exercise/experiment.tsx
is this file still needed?

2023-11-08 17:29 UTC, elbotho commented on public/_assets/img/exercise/exercise-generation-loading-sparkles.svg
https://sentry.io/answers/delete-a-file-from-a-git-repository/

2023-11-08 17:29 UTC, elbotho commented on src/components/content/exercises/exercise-generation-wizard/difficulty.tsx
> +  const { strings } = useLoggedInData() as LoggedInData
if you are sure that at this point the user will always be logged in you could also use `!` to shorten this:
```ts
  const { strings } = useLoggedInData()!
```

If you are not entirely sure that's what I usually use:
```ts
  const loggedInData = useLoggedInData()
  if(!loggedInData) return null // or handle somehow
```

and to simplify your component I'd use:
```suggestion
  const difficultyStrings = useLoggedInData()!.strings.ai.exerciseGeneration.difficulty
  …
```
(here and in the other comps)

2023-11-08 17:29 UTC, elbotho commented on src/components/content/exercises/exercise-generation-wizard/grade.tsx
> +      <div className={`${isSummary ? '' : 'mb-8'} flex items-center`}>
please prefer `clsx` for className logic.

2023-11-13 11:56 UTC, Entkenntnis commented on shared/tailwind-base.cjs
> +  400: '#ffd8a6',
a) it's the wrong file
b) it's unused
I'm going to remove this

2023-11-13 14:50 UTC, merged

2023-11-13 15:34 UTC, elbotho commented
small remark:
for this and the other dropdowns:
<img width="467" alt="image" src="https://github.com/serlo/frontend/assets/1258870/04f73c99-58e9-413b-b2ef-12d55be071d0">
As a user I'm not sure if I need to select and if the generation will use a default value if I do not choose something here.

2023-11-13 16:01 UTC, elbotho commented
"Solution with 1 number"
was a bit confusing for me since we usually call the type "Input Exercise" and also since "Solution" is ambiguous here.
<img width="385" alt="image" src="https://github.com/serlo/frontend/assets/1258870/6d1eb4c7-e61a-4c5b-bd5d-e01689a58974">

2023-11-13 16:10 UTC, elbotho commented
missing hover state:
<img width="240" alt="image" src="https://github.com/serlo/frontend/assets/1258870/e632aa02-a653-4dbf-bc96-6ac60a83c22e">

2023-11-13 16:23 UTC, elbotho commented
the changes in the Modal comp break this existing close button:
<img width="770" alt="image" src="https://github.com/serlo/frontend/assets/1258870/cd26bbfd-b191-40aa-a04c-cb02441e9966">

2023-11-13 16:27 UTC, elbotho reviewed
another round :)

2023-11-13 16:27 UTC, elbotho commented on src/components/content/exercises/menu-button.tsx
since this is only used in `exerercise-generation-wizard` I'd probably move it into that folder

2023-11-13 16:27 UTC, elbotho commented on src/components/user-tools/foldout-author-menus/author-tools.tsx
> +      exerciseFolder: [UuidType.Exercise, UuidType.ExerciseGroup, 'AI'],
I don't like this addition here. AI is not a `UuidType`, it's a tool that allows `Exercise` and `ExerciseGroup` to be created. Could you just add a check below and add the additional SubItem when `Exercise` is mapped?

2023-11-13 16:27 UTC, elbotho commented on src/components/user-tools/foldout-author-menus/author-tools.tsx
> +      exerciseFolder: [UuidType.Exercise, UuidType.ExerciseGroup, 'AI'],
something like: 

``` ts
const showAiItem =
  entityType === UuidType.ExerciseGroup &&
  !isProduction &&
  canUseAiFeatures

return (
  <>
    <SubItem
      key={title}
      title={title}
      href={`/entity/create/${entityType}/${data.id}`}
    />
    {showAiItem ? (
      <SubItem
        key="ai"
        title={loggedInStrings.ai.exerciseGeneration.buttonTitle}
        onClick={showWizard}
        icon={faWandSparkles}
      />
    ) : null}
  </>
)
```

2023-11-13 16:27 UTC, elbotho commented on src/components/user-tools/foldout-author-menus/author-tools.tsx
> +
```suggestion
  
```

2023-11-13 16:27 UTC, elbotho commented on src/helper/ai-generated-exercises/data-conversion.ts
> +export interface IEditorExerciseData {
please don't add `I` to interface names and I'd prefer something more specific so other ppl do not confuse it for a more general type.

2023-11-13 16:27 UTC, elbotho commented on src/helper/error-boundary.tsx
> +      return <h1>Something went wrong.</h1>
maybe make more helpful and add i18n?

2023-11-13 16:27 UTC, elbotho commented on src/components/content/exercises/exercise-preview-page.tsx
> +            }
I have to investigate as soon as staging is back up, but it seems it might be easier to move this into the editing view in the first place. Clicking on the ai menu button would then open the `/entity/create/…` route directly and open the wizard there. Then you don't have to pass the state around.

2023-11-13 16:27 UTC, elbotho commented on src/components/content/exercises/menu-button.tsx
> +export const MenuButton: React.FC<MenuButtonProps> = ({
I'd prefer `function …`

2023-11-13 16:27 UTC, elbotho commented on src/components/content/exercises/menu-button.tsx
> +export const MenuItem: React.FC<MenuItemProps> = forwardRef(
I'd prefer `function …`

2023-11-13 16:27 UTC, elbotho commented on src/components/content/exercises/exercise-generation-wizard.tsx
> +const NavigationFooter: React.FC<NavigationFooterProps> = ({
I'd prefer `function …`

2023-11-13 16:27 UTC, elbotho commented on src/components/content/exercises/exercise-generation-wizard/topic.tsx
> +export const Topic: React.FC<TopicProps> = ({
I'd prefer `function …`

2023-11-13 16:27 UTC, elbotho commented on src/components/content/exercises/exercise-preview-page.tsx
> +export const ExercisePreviewPage: React.FC<ExercisePreviewPageProps> = ({
I'd prefer `function …`

2023-11-13 16:27 UTC, elbotho commented on src/components/content/exercises/exercise-generation-wizard.tsx
> +export const ExerciseGenerationWizard: React.FC<
I'd prefer `function …`

2023-11-13 16:27 UTC, elbotho commented on src/serlo-editor/plugins/serlo-template-plugins/helpers/content-loaders/content-loaders.tsx
> +
should not be necessary any more