feat: Renaming "NBP" -> "Mein Bildungsraum"
serlo/frontend pull request #3053
Opened 2023-10-31 18:07 UTC by kulla

2023-10-31 18:09 UTC, Entkenntnis commented on src/data/de/index.ts
> +        code1010002: "Über „Mein Bildungsraum“ anmelden",
don't change the german translation, these are managed by crowdin

2023-10-31 21:55 UTC, elbotho requested changes

2023-10-31 21:55 UTC, elbotho commented on src/components/pages/data-wallet.tsx
> +              Lade dir die „Mein Bildungsraum Wallet App“ auf dein Smartphone.
Lade dir die App „Mein Bildungsraum: Wallet“ auf dein Smartphone.

2023-11-01 15:24 UTC, Entkenntnis approved these changes

2023-11-01 15:43 UTC, kulla commented
@elbotho @Entkenntnis Thank you for the feedback! @hugotiburtino Thank you for overtaking the PR!

2023-11-01 15:44 UTC, merged