Remove global JSX styles from modal
serlo/frontend pull request #3120
Opened 2023-11-22 15:36 UTC by CodingDive

Please check the save-modal in the review. I think the responsiveness is a little bit nicer now too. If you like the before better (instead of a fat button, we can just add flex-wrap).

## Before

![image](https://github.com/serlo/frontend/assets/28842311/4ddc6613-9619-41fd-ad11-7977c9087baa)

## After

![image](https://github.com/serlo/frontend/assets/28842311/3f2e4a31-ef9a-4aa3-a80b-ec56b3e50939)

2023-11-22 15:38 UTC, CodingDive commented on src/serlo-editor/plugins/serlo-template-plugins/helpers/content-loaders/revision-history-loader.tsx
> +          tableClassName="mt-12 !w-auto"
Need the !important here because of the custom value `w-[500px]` inside the ModalWithCloseButton component

2023-11-22 15:51 UTC, elbotho commented
weird positioning for me (overlaps bottom of window)
<img width="1384" alt="image" src="https://github.com/serlo/frontend/assets/1258870/5b9b5d37-6c97-48ca-a403-8bdf71bb551d">
<img width="1369" alt="image" src="https://github.com/serlo/frontend/assets/1258870/cea0bb4c-1aa5-4fc5-a0fc-c3eace5aec3f">

2023-11-22 16:40 UTC, elbotho commented
- can we have a maxwidth for my tv? ;)
- revision modal still broken
<img width="1213" alt="image" src="https://github.com/serlo/frontend/assets/1258870/75911c1b-a0cc-4a1b-a64b-f4280d9ba37a">

2023-11-22 19:22 UTC, CodingDive commented
I do prefer the simplicity of
https://github.com/serlo/frontend/pull/3121

2023-11-22 20:42 UTC, elbotho requested changes
problems with settings modal

2023-11-22 21:07 UTC, CodingDive commented
> problems with settings moda

Yeah, as the global styles no longer get applied, a lot of the usages will be broken.

Toolbar settings of 
Multimedia
Image 
Audio
...

2023-11-23 09:39 UTC, Entkenntnis commented
@CodingDive Thank you for tackling this! As you have noticed, we are defining the styles in three different places and it's a bit difficult to untangle. It would be very helpful to sort this out properly once and for all and remove the global styles.

2023-11-23 14:34 UTC, Entkenntnis commented
@CodingDive can you give an update if the issues botho has noted are solved in this PR?

2023-11-23 14:57 UTC, CodingDive commented
The modal of the settings should look good now, however, I just saw that the `lightbox` component is broken 

![image](https://github.com/serlo/frontend/assets/28842311/320547b9-64f5-4670-844d-0cbe38382664)

Edit: Should work now, I don't like the hack though

2023-11-23 15:31 UTC, elbotho approved these changes

2023-11-23 15:31 UTC, elbotho commented on src/components/modal-with-close-button.tsx
> +  className?: string | ReactModal.Classes
```suggestion
  className?: string
```
Not needed, right?

2023-11-23 16:11 UTC, elbotho approved these changes

2023-11-23 16:11 UTC, merged