Add SpoilerOpened tracking event, for saving in PlanetScale
serlo/frontend pull request #3495
Opened 2024-03-12 08:00 UTC by shn-srl

Sends a SpoilerOpened tracking event to Planetscale

To confirm:

[ ] Is all the required information being saved ?

- Important: PlanetScale migration also needs to run

https://app.planetscale.com/serlo/serlo_planetscale/test-spoiler-tracking/

![image](https://github.com/serlo/frontend/assets/161819227/0e8ac080-43e1-4f3e-819e-709b574f8c71)

2024-03-12 10:03 UTC, shn-srl commented on packages/editor/src/plugins/spoiler/static.tsx
> +      entityId: -1, // should this be a real id?
This needs to be double checked.

If entity id is needed, what id is it? I see string Ids but the abSubmission expects an int

2024-03-12 11:19 UTC, Entkenntnis requested changes
Two minor things:

- Can you revert the db change?
- Check if entity id is one of the three we use this event for

2024-03-14 08:29 UTC, shn-srl commented
> Two minor things:
> 
>     * Can you revert the db change?
> 
>     * Check if entity id is one of the three we use this event for

DB change was on a development branch, which is now deleted :heavy_check_mark: 

Added EntityId check :heavy_check_mark:

2024-03-14 09:53 UTC, Entkenntnis approved these changes

2024-03-14 09:53 UTC, Entkenntnis requested changes
move code to integration and out of editor repo

2024-03-14 16:39 UTC, Entkenntnis approved these changes
Thank you

2024-03-14 16:39 UTC, merged