chore(editor): Update editor roadmap with Silvia
serlo/frontend pull request #3814
Opened 2024-05-21 16:33 UTC by CodingDive

- [x] Add fill in the gap table typing example
- [x] Add fill in the gap table drag & drop example
- [x] Remove `beta` tag
- [x] Add Moodle and Edusharing as popular LMS integrations
- [x] Change name of Quinn
- [x] Replace Anna with myself
- [x] Add Gregor as product owner
- [x] Add two examples for the fill in the gap
- [x] Make partners take 2 rows on bigger screens

2024-05-21 22:03 UTC, elbotho requested changes
Fill in the Gap Example is broken for me. Some Gaps don't work and there are not enough draggable items?
<img width="994" alt="image" src="https://github.com/serlo/frontend/assets/1258870/094bfadf-b51d-40a3-9846-db28bc940098">

Maybe we could shorten the "Latest Releases" column a bit?
I'd probably leave out:
- Improved focus management (not super exciting)
- Impact dashboard – supporting authors with usage data (not actually part of editor?)
- and maybe "Directly link to content sections" (not super exciting, was already possible before)

2024-05-21 22:03 UTC, elbotho commented on apps/web/src/components/pages/editor/editor-team.tsx
> +    firstName: 'Quinn',
@Entkenntnis just to make sure, are you fine with this?

2024-05-21 22:23 UTC, elbotho commented on apps/web/src/components/pages/editor/education-plugin-examples.tsx
> +export const BoxExample = (
I don't really care here but for context: I lowercased them because they are not react components.

2024-05-22 07:15 UTC, CodingDive commented on apps/web/src/components/pages/editor/editor-team.tsx
> +    firstName: 'Quinn',
I asked :blush:

2024-05-22 07:16 UTC, CodingDive commented on apps/web/src/components/pages/editor/education-plugin-examples.tsx
> +export const BoxExample = (
Feels like a constant to me, that we are PascalCasing. Mostly did it for consistency with some of them that were already starting upper cased like the exercise examples

2024-05-22 07:19 UTC, CodingDive commented
> Fill in the Gap Example is broken for me. Some Gaps don't work and there are not enough draggable items?

So good that you mention this! These are actually 2 fill in the gap examples. Top one for typing and bottom one for drag & drop. I'll make this more clear.

Thank you also for the suggestions on what we can remove! Will implement your, Silvias and Vickys feedback and rerequest your review

2024-05-22 08:10 UTC, elbotho commented on apps/web/src/components/pages/editor/education-plugin-examples.tsx
> +export const BoxExample = (
> Feels like a constant to me, that we are PascalCasing

who, where? E.g. this folder is full of constant definitions in lower case.

2024-05-22 18:02 UTC, CodingDive commented on apps/web/src/components/pages/editor/education-plugin-examples.tsx
> +export const BoxExample = (
These were already starting with an upper case. 

SCExample
MCExample

Let me know if you do care, and I'm happy to change everything to lowercase :relaxed:

2024-05-23 14:14 UTC, elbotho approved these changes
thank you. 
Only think (but optinal): I think only one table Blanks-Example is better for simplicity. I'd remove `Exercise with table input`.

2024-05-23 16:19 UTC, merged