wip: add native newsletter popup
serlo/frontend pull request #3945
Opened 2024-07-08 13:48 UTC by elbotho

@Entkenntnis what do you think of this popup implementation?
Different approach to your scrollup code, not sure what is actually more performant but since the listeners get removed as soon as the popup did show it's probably fine.

todos: 
- activate mailchimp landing page with form and link in popup
- add new localstorage var to relevant privacy documents

2024-07-25 10:59 UTC, elbotho commented
ping @Entkenntnis  (see slack)

2024-07-25 14:23 UTC, CodingDive requested changes
Looks good! Just few typos

2024-07-25 14:23 UTC, CodingDive commented on apps/web/src/components/scripts/newsletter-popup.tsx
> +  const [alredySeen, setAlredySeen] = useState(false)
already*

2024-07-25 14:23 UTC, CodingDive commented on apps/web/src/components/scripts/newsletter-popup.tsx
> +          alt="Das Serlo Team läd dich ein den Newsletter zu abbonieren."
lädt*

2024-07-25 14:23 UTC, CodingDive commented on apps/web/src/components/scripts/newsletter-popup.tsx
> +          <b>Kurs und prägnant</b>:<br />
Kurz* (außer es ist ein Wortspiel in Kursen 😁)

2024-07-25 14:46 UTC, elbotho commented
> Looks good! Just few typos

🙈 Thank you.

2024-07-25 17:01 UTC, CodingDive approved these changes
Thank you!

2024-07-26 13:04 UTC, Entkenntnis approved these changes
works for me and looks good

2024-07-26 13:50 UTC, merged