feat(plugin-rows): split BlanksExercise in plugin menu
serlo/frontend pull request #4062
Opened 2024-09-03 07:44 UTC by hejtful

Linear issue: PE-69

It's a lot of changes, but I didn't think of a way to do it with fewer changes. Feedback very welcome

2024-09-04 10:08 UTC, elbotho requested changes

2024-09-04 10:08 UTC, elbotho commented on apps/web/src/data/en/index.ts
> +          blanksExerciseDragAndDrop: 'Fill In The Blanks Exercise',
This should be a different string, right?

2024-09-04 10:08 UTC, elbotho commented on apps/web/src/data/en/index.ts
> +          title: 'Drag&Drop exercise',
Is that a good title since we also have other exercises that use drag&drop?
Maybe "Drag & Drop Fill in the blanks"? 
(maybe ping @GregorZupan)

2024-09-04 10:08 UTC, elbotho commented on apps/web/src/data/en/index.ts
> +            'Create a fill-in-the-gap text or a table where the correct answers are inserted via drag and drop.',
```suggestion
            'Create a fill in the blanks exercise (text or table) where learners add the answers via drag and drop.',
```

btw: the "fill-in-the-gap" part is also incorrect in the original string above.

2024-09-04 10:10 UTC, elbotho commented
A little off topic:
@GregorZupan This view is not really working any more, but it's also not really supported any more, right?
![image](https://github.com/user-attachments/assets/214510f6-c776-4e43-9dfc-6d2e87e6efe6)

(currently you can for example remove an input exercise from the plugin toolbar and get this view)

Maybe we should remove it and add an "Textaufgabe" Option in the Exercise Plugin Toolbar instead?
(then this select menu would be the only way to change an exercise)

![image](https://github.com/user-attachments/assets/e7c6df20-706b-40c2-a3ba-449a489c0450)

2024-09-04 10:30 UTC, hejtful commented on apps/web/src/data/en/index.ts
> +            'Create a fill-in-the-gap text or a table where the correct answers are inserted via drag and drop.',
The strings come from [this document](https://docs.google.com/document/d/1Jqd3qqRtBX-J3dKwC7-rohDqZGTSGyNNvPq5XXaKllY/edit#heading=h.ubjbe6nuxwf2) and were discussed with @GregorZupan , so I'll leave this to him.

2024-09-04 10:32 UTC, hejtful commented on apps/web/src/data/en/index.ts
> +          blanksExerciseDragAndDrop: 'Fill In The Blanks Exercise',
Good point, thanks! I'll wait for [this comment](https://github.com/serlo/frontend/pull/4062/files#r1743439889) to be resolved, and then fix this.

2024-09-04 12:06 UTC, GregorZupan commented on apps/web/src/data/en/index.ts
> +          title: 'Drag&Drop exercise',
Good Point! Do we need both the english and german strings for the plugin(s)?

2024-09-04 12:34 UTC, elbotho commented on apps/web/src/data/en/index.ts
> +          title: 'Drag&Drop exercise',
Having both would be easiest.

2024-09-05 13:30 UTC, GregorZupan commented on apps/web/src/data/en/index.ts
> +            'Create a fill-in-the-gap text or a table where the correct answers are inserted via drag and drop.',
Proposal accepted! 

I'll edit it in my tooltip document

2024-09-05 13:30 UTC, GregorZupan commented on apps/web/src/data/en/index.ts
> +            'Create a fill-in-the-gap text or a table where the correct answers are inserted via drag and drop.',
I also changed the german copy a bit

2024-09-05 13:45 UTC, elbotho commented on apps/web/src/data/en/index.ts
> +          title: 'Fill in the Blanks',
```suggestion
          title: 'Fill in the Blanks (typing)',
```

2024-09-05 13:49 UTC, elbotho approved these changes
:godmode:

2024-09-05 13:52 UTC, merged