ci(editor): Write custom github action for generating changelog from PR names and throw out the changeset package
serlo/frontend pull request #4171
Opened 2024-10-09 15:37 UTC by CodingDive

Split it into two actions. One that does the automated changelog based on branch names (we can still change it manually), runs on every branch. And the existing github action that publishes it to npm and pushes the tag as a release to Github. This one only runs on staging

2024-10-09 19:22 UTC, hugotiburtino requested changes

2024-10-09 19:22 UTC, hugotiburtino commented on .github/workflows/editor.yaml
> +        uses: actions/create-release@v1
This action is not maintained anymore. You could use one of the maintained actions that are listed in the readme of [actions/create-release](https://github.com/actions/create-release).

I thought you would like to have a changelog also. Do you plan to do it afterwards?

2024-10-09 19:28 UTC, hugotiburtino commented on .github/workflows/editor-changelog.yaml
> +name: Generate Editor Changelog
Interesting code. 
Have you searched for actions out there that do the same? Because, if there is any, we wouldn't have to maintain this code here.

2024-10-09 19:34 UTC, CodingDive commented on .github/workflows/editor-changelog.yaml
> +name: Generate Editor Changelog
It's very specific to our monorepo structure and we only care about changes in /packages/editor. I couldn't find a good one with monorepo support and thought it'd be easier to write the code myself

2024-10-10 11:09 UTC, hugotiburtino commented on .github/workflows/editor.yaml
> +        with:
BTW, I see that you create a changelog in the other workflow, but the body of the release remains clean. Is that intentional?

2024-10-10 15:13 UTC, CodingDive commented on .github/workflows/editor.yaml
> +        uses: actions/create-release@v1
Thank you, Hugo! 

I decided to go with this one. Do we need to add it from the market place or will the github action runner pick it up automatically? 

https://github.com/elgohr/Github-Release-Action

2024-10-10 15:14 UTC, CodingDive commented on .github/workflows/editor.yaml
> +        with:
It was not intentional, I think it should extract the changelog of /editor/packages correctly, but I haven't been able to run the code to test it out :crossed_fingers:

2024-10-10 16:05 UTC, hugotiburtino commented on .github/workflows/editor.yaml
> +          if npm view @serlo/editor@$CURRENT_VERSION > /dev/null 2>&1; then
There is some repetition in this part.
What about merging both?

2024-10-10 16:06 UTC, hugotiburtino commented on .github/workflows/editor.yaml
> +          CURRENT_VERSION=$(node -p "require('./packages/editor/package.json').version")
If you stored the CURRENT_VERSION before, you just need to retrieve it from `env.`

2024-10-10 16:08 UTC, hugotiburtino approved these changes

2024-10-10 22:31 UTC, hugotiburtino commented on .github/workflows/editor.yaml
> +        uses: actions/create-release@v1
github action runner pick it up automatically

2024-10-10 22:41 UTC, hugotiburtino commented on packages/editor/.prettierignore
> +CHANGELOG.md
Instead of gitignoring it, what about adding a prettier step `yarn prettier -w packages/editor/CHANGELOG.md` before commiting it?

2024-10-11 08:01 UTC, CodingDive commented on packages/editor/.prettierignore
> +CHANGELOG.md
Good idea! Let's try it :crossed_fingers:

2024-10-11 10:53 UTC, merged