fix(link-plugin): Allow absolute serlo urls in integrations
serlo/frontend pull request #4289
Opened 2024-11-15 15:47 UTC by CodingDive

https://linear.app/serlo/issue/DEV-233/bug-inserting-links-is-confusing

The problem was that it strips the serlo.org and then treats every URL as a relative URL. This lead to you being lead to some weird moodle/chancenwerk pages that don't exist and yield 404s

2024-11-18 12:54 UTC, elbotho requested changes
Thanks you for looking into it!

2024-11-18 12:54 UTC, elbotho commented on packages/editor/src/plugins/text/utils/link.ts
> +  yieldAbsoluteUrl: boolean = false
I'd prefer to also call it `isSerlo` inside this function since we only allow serlo absolute urls and this is all still very serlo specific.

2024-11-18 12:54 UTC, elbotho commented on packages/editor/src/plugins/text/utils/link.ts
> +  yieldAbsoluteUrl: boolean = false
Follow up: If `isSerlo` is false there is not much happening. I think this function might be simpler with a 
`if(!isSerlo) return …` early return and keeping the rest of the code as is.

2024-11-19 13:10 UTC, elbotho commented
@CodingDive does it make sense to support entering just a serlo Id outside of serlo?

2024-11-19 13:13 UTC, CodingDive commented
> @CodingDive does it make sense to support entering just a serlo Id outside of serlo?

I can also change our placeholder. There it says /1234. I think it's a nice convenience, but not sure how often it'll be used.

![image](https://github.com/user-attachments/assets/d7567d93-7e5b-45ad-a942-c5485fd39fba)

2024-11-19 16:55 UTC, elbotho approved these changes

2024-11-19 16:55 UTC, elbotho commented on packages/editor/src/plugins/text/utils/link.ts
> +  isSerlo: boolean = true
```suggestion
  isSerlo: boolean,
  instance?: string
```

2024-11-20 13:13 UTC, merged