User Profiles
serlo/frontend pull request #679
Opened 2020-11-28 11:13 UTC by elbotho

rebase of #573

### example profile
…/user/profile/18981

### issue
https://github.com/serlo/frontend/issues/677

### status
- Uses mockup data for now (because descriptions are not part of the staging data (returns NULL)

2020-11-28 20:26 UTC, inyono commented
FYI: staging has anonymized data (e.g. removes all email addresses & descriptions of users). This would work in prod.

2020-12-01 12:19 UTC, elbotho commented
@Entkenntnis okay! This is ready for review now. 
As per your suggestion I implemented the link to /user/profile/username in the menu (best solution) and added a simple fallback redirect for /user/me and /user/profile that we can remove after 100%.

2020-12-01 12:43 UTC, Entkenntnis requested changes
Looks fine! (Finally getting this done)

2020-12-01 12:43 UTC, Entkenntnis commented on src/components/content/author-tools.tsx
> +        author tools
Hm, looks superfluous here

2020-12-01 12:43 UTC, Entkenntnis commented on src/components/pages/user/profile-community-banner.tsx
> +      const parts = bannerContent[key].ownProfileMessage.split('%no%')
We have something better now :)

2020-12-01 12:43 UTC, Entkenntnis commented on src/components/pages/user/profile-community-banner.tsx
> +        {bannerContent[key].otherUserProfileMessage.replace(
Same here :)

2020-12-01 13:20 UTC, Entkenntnis approved these changes

2020-12-01 13:22 UTC, merged

2020-12-01 13:22 UTC, elbotho commented
Thanks @Entkenntnis