Manage subscriptions and pages refactor
serlo/frontend pull request #806
Opened 2021-01-23 20:47 UTC by elbotho

Supersedes #805

@Entkenntnis Sorry, this a bit much in one go,
It's the page refactoring and also a new feature in one go.

http://localhost:3000/subscriptions/manage

2021-01-23 22:21 UTC, Entkenntnis commented
Wow, that's a big one xD. I will take a look at it 👍

2021-01-24 11:37 UTC, Entkenntnis requested changes
Looks good! Some small leftovers from previous refactoring. I will merge after deployment, so we have time to test it on staging.

2021-01-24 11:37 UTC, Entkenntnis commented on src/pages/_app.tsx
> +}
Using normal AppProps should suffice here. (InitialProps will be removed soon and replaced by page specific prop types)

2021-01-24 11:37 UTC, Entkenntnis commented on src/pages/_app.tsx
>      <React.StrictMode>
Not necessary anymore

2021-01-24 11:37 UTC, Entkenntnis commented on src/pages/spenden.tsx
> +}
Not necessary

2021-01-24 12:02 UTC, elbotho commented
@Entkenntnis Thank you for the review! Just added the changes.
Jup merging after Deploy is probably a good idea 👍 
Will base next PR on this, check?

2021-01-25 08:32 UTC, merged